export const DATA = {
  name: 'Parth Gandhi',
  location: 'New Delhi, India',
  initials: 'DV',
  url: 'https://dillion.io',
  locationLink: 'https://www.google.com/maps/place/sanfrancisco',
  description:
    'Full Stack developer who enjoys turning ideas into reality and solving complex problems. Always exploring new technologies. Active contributor on GitHub and Twitter.',
  summary:
    'I build web apps that look great, work smoothly, and might even make you laugh while you’re using them. In the past, I pursued a bachelor degree in computer science, interned at bubbling startups , and built my own projects for fun. ',
  contact: {
    email: 'iampgandhi@gmail.com',
    tel: '+91 7011-989-645',
    social: {
      GitHub: {
        name: 'GitHub',
        url: 'https://github.com/iamparth2002',
      },
      LinkedIn: {
        name: 'LinkedIn',
        url: 'https://www.linkedin.com/in/parth-gandhi-bb8aab135/',
      },
      X: {
        name: 'X',
        url: 'https://x.com/iamparth2002',
      },
    },
  },
  work: [
    {
      company: 'Yatiken Software Solutions',
      href: 'https://brihatinfotech.com/',
      badges: [],
      type: 'On-site',
      location: 'New Delhi, India',
      title: 'Full Stack Developer',
      logoUrl: '/bi.png',
      start: 'Sept 2024',
      end: 'Dec 2024',
      list: [
        'Designed, developed, and deployed scalable web applications using the MERN stack (MongoDB, Express.js, React.js, Node.js) to meet client-specific needs, resulting in a 30% faster project delivery rate.',
        'Shipdart: Built a shipping management system integrating multi-courier APIs, reducing shipment tracking issues by 40%',
        'Adigo: Developed an e-commerce platform for agriculture equipment with real-time inventory tracking, leading to an increase in vendor adoption.',
        'Edural: Engineered an LMS with student, admin, and teacher dashboards, onboarding 100+ users and improving education workflow efficiency.',
        'Optimized application performance by reducing API response times by 35% and enhancing database query efficiency using Mongoose and Postman.',
        'Utilized Agile methodologies, participating in sprint planning, daily standups, and code reviews, resulting in a reduction in project bugs.',
        'Leveraged tools like Git, Jira, and Docker for version control, project management, and streamlined deployment processes.',
      ],
      description: `Developed The Colorants, a full stack web application, handling both frontend (Next.js, Zod, React Hook Form, Tailwind CSS, ShadCN) and backend (Node.js, Express, MongoDB, Mongoose, Cloudinary for image storage), including deployment on AWS.`,
      technologies: [
        'Next.js',
        'Next Auth',
        'TailwindCSS',
        'MongoDB',
        'NodeJS',
        'ExpressJS',
        'MongoDB',
        'AWS',
        'ReactJS',
      ],
    },
    {
      company: 'Brihat Infotech',
      type: 'Hybrid',
      href: 'https://brihatinfotech.com/',
      badges: [],
      location: 'New Delhi, India',
      title: 'Full Stack Developer',
      logoUrl: '/bi.png',
      start: 'Jan 2024',
      end: 'Jun 2024',
      list: [
        'Designed and deployed The Colorants, a full-stack web app using Next.js, Node.js, and MongoDB, achieving 100% uptime during client onboarding.',
        'Onboarded 50+ salons and 500+ users, providing a seamless and intuitive interface using Tailwind CSS, Zod, and ShadCN for UI consistency.',
        'Reduced backend response times by 30% through query optimization and efficient API handling.',
        'Fixed 50+ UI/UX issues by optimizing React components and reducing unnecessary re-renders, leading to a 1.5-second reduction in page load times.',
        'Integrated Cloudinary for optimized image storage and enhanced scalability on AWS infrastructure.',
      ],
      description: `Developed The Colorants, a full stack web application, handling both frontend (Next.js, Zod, React Hook Form, Tailwind CSS, ShadCN) and backend (Node.js, Express, MongoDB, Mongoose, Cloudinary for image storage), including deployment on AWS.`,
      technologies: [
        'Next.js',
        'Next Auth',
        'TailwindCSS',
        'MongoDB',
        'NodeJS',
        'ExpressJS',
        'MongoDB',
        'AWS',
        'ReactJS',
      ],
    },
    {
      company: 'Accent Technosoft',
      href: 'https://www.accenttechnosoft.com/',
      badges: [],
      type: 'Remote',
      location: 'Coimbatore, India',
      title: 'Frontend Developer',
      logoUrl: '/accent-technosoft.png',
      start: 'Dec 2022',
      end: 'Jan 2023',
      list: [
        'Developed responsive landing pages using React.js, Material-UI, and Bootstrap, achieving a 98% Lighthouse score for performance and accessibility.',
        'Created reusable components to streamline development and improve design consistency.',
        'Collaborated with designers to implement pixel-perfect, responsive UI components, ensuring cross-browser compatibility and improving page load performance.',
      ],
      technologies: [
        'React.js',
        'BootStrap',
        'Material-ui',
        'TailwindCSS',
        'HTML',
        'CSS',
        'Javascript',
      ],
    },
  ],
  projects: [
    {
      title: 'RemindMe',
      href: 'https://remind-me-project.vercel.app/',
      active: true,
      description:
        'RemindMe is a task management system designed to help you stay organized and productive with an intuitive UI and seamless user authentication.',
      technologies: [
        'Next.js',
        'TypeScript',
        'TailwindCSS',
        'Prisma',
        'PostgreSQL',
        'Shadcn UI',
      ],
      github: 'https://github.com/iamparth2002/remindMe',
      source: 'https://remind-me-project.vercel.app/',
      image: '/remindMe.png',
    },
    {
      title: 'Promptopia',
      href: 'https://promptopia-project-app.vercel.app/',
      active: true,
      description:
        'Developed an AI-prompting tool providing users with a platform for prompt sharing.',
      technologies: [
        'Next.js',
        'NodeJS',
        'ExpressJS',
        'Next Auth',
        'TailwindCSS',
        'MongoDB',
      ],
      github: 'https://github.com/iamparth2002/promptopia-app',
      source: 'https://promptopia-project-app.vercel.app/',
      image: '/promptopia.png',
    },
    {
      title: 'Echo Blogs',
      href: 'https://echo-blogs.vercel.app/',
      active: true,
      description: `Developed Echo Blogs, a MERN stack web application, enabling users to create, edit, and manage blog
posts with rich text editing, commenting feature and onboarded 20+ authors successfully.`,
      technologies: [
        'Next.js',
        'NodeJS',
        'ExpressJS',
        'Next Auth',
        'TailwindCSS',
        'MongoDB',
      ],
      github: 'https://github.com/iamparth2002/blog-client',
      source: 'https://echo-blogs.vercel.app/',
      image: '/echo.png',
    },
    {
      title: 'CloudNova',
      href: 'https://cloudnova-project.vercel.app/',
      active: true,
      description:
        'CloudNova is a cloud storage and file-sharing platform that lets you easily share files with anyone via email or a link through your favorite social media accounts.',
      technologies: [
        'Next.js',
        'Typescript',
        'Firestore',
        'Resend',
        'Firebase',
        'TailwindCSS',
        'Shadcn UI',
        'Magic UI',
      ],
      github: 'https://github.com/iamparth2002/cloudNova',
      source: 'https://cloudnova-project.vercel.app/',
      image: '/cloudNova.png',
    },
    {
      title: 'SmartCV',
      href: 'https://ai-resume-builder-project.vercel.app/',
      active: true,
      description:
        '"Developed an AI-powered Resume Builder application enabling users to add information dynamically with AI assistance.',
      technologies: [
        'React.js',
        'Typescript',
        'Strapi',
        'Gemini AI',
        'TailwindCSS',
        'Shadcn UI',
        'Clerk',
        'NodeJS',
        'ExpressJS',
      ],
      github: 'https://github.com/iamparth2002/ai-resume-builder',
      source: 'https://ai-resume-builder-project.vercel.app/',
      image: '/smartCV.png',
    },
    
    {
      title: 'FinanSmart',
      href: 'https://finansmart-app.vercel.app/',
      active: true,
      description:
        'FinanSmart leverages AI to help you manage expenses within budget allocations. Track spending, get personalized insights, and optimize your financial decisions effortlessly.',
      technologies: [
        'Next.js',
        'Drizzle',
        'PostgreSQL',
        'TailwindCSS',
        'Shadcn UI',
        'Gemini AI',
        'Framer Motion',
      ],
      github: 'https://github.com/iamparth2002/FinanSmart',
      source: 'https://finansmart-app.vercel.app/',
      image: '/finansmart.png',
    },
    {
      title: 'Pickup Line generator',
      href: 'https://pickup-line-generator-ruby.vercel.app/',
      active: true,
      description:
        'This fun tool generates witty and creative pickup lines using AI, perfect for breaking the ice or just having a laugh.',
      technologies: [
        'Next.js',
        'Typescript',
        'PostgreSQL',
        'Supabase',
        'TailwindCSS',
        'Shadcn UI',
        'Gemini AI',
      ],
      github: 'https://github.com/iamparth2002/pickup-line-generator',
      source: 'https://pickup-line-generator-ruby.vercel.app/',
      image: '/pickup.png',
    },
  ],
};
